#### Тема “Вычисления с помощью Numpy”
#### Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента

In [1]:
import numpy as np

In [13]:
a = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [14]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
mean_a = a.mean(axis = 0)

In [16]:
mean_a

array([2. , 8.4])

##### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [46]:
a_centered = a - mean_a 

In [47]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

##### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 

In [48]:
a1 = a_centered[0:, 0]

In [49]:
a1

array([-1.,  0.,  1.,  1., -1.])

In [50]:
a2 = a_centered[0:, 1]

In [51]:
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [52]:
a_centered_sp = np.dot(a1,a2)

In [53]:
a_centered_sp

8.0

Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [59]:
a_centered_sp / (a.shape[0] - 1)

2.0

##### Задание 4**
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [62]:
m = a.transpose()

In [63]:
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [68]:
np.cov(m)

array([[1. , 2. ],
       [2. , 4.3]])

In [69]:
m[0, 1]

2

#### Тема “Работа с данными в Pandas”
##### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [70]:
import pandas as pd

In [71]:
author = pd.DataFrame({'author_id':[1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']})

In [72]:
author

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [73]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],  
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [74]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

##### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [75]:
authors_price = pd.merge(author, book, on = 'author_id', how = 'outer')

In [76]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [85]:
top5 = authors_price.nlargest(5, 'price')

In [86]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

##### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [160]:
authors_stat_min = authors_price.groupby('author_name').agg({'price': 'min'})

In [161]:
authors_stat_min = authors_stat_min.rename(columns={'price':'min_price'})

In [162]:
authors_stat_min

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [123]:
authors_stat_max = authors_price.groupby('author_name').agg({'price': 'max'})

In [124]:
authors_stat_max = authors_stat_max.rename(columns={'price':'max_price'})

In [125]:
authors_stat_max

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [144]:
authors_stat_mean = authors_price.groupby('author_name').agg({'price': 'mean'})

In [145]:
authors_stat_mean = authors_stat_mean.rename(columns={'price':'mean_price'})

In [146]:
authors_stat_mean

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

### 1 способ через merge

In [154]:
authors_stat_1 = pd.merge(authors_stat_min, authors_stat_max, on = 'author_name', how = 'outer')

In [155]:
authors_stat = pd.merge(authors_stat_1, authors_stat_mean, on = 'author_name', how = 'outer')

In [156]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### 2 способ через concat

In [151]:
authors_stat = pd.concat([authors_stat_min, authors_stat_max, authors_stat_mean], axis = 1)

In [152]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000